gosb:
  data: db
#  dataLayer: "redis"
micronaut:
  application:
    name: microGosb
redis.uri: redis://localhost
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

logger:
  levels:
    io.micronaut.context.condition: ERROR
    org.schors: TRACE



