gosb:
#  data: db
  data: redis
micronaut:
  router:
    static-resources:
      assets:
        enabled: true
        mapping: /**
        paths: file:./dist/battle
  application:
    name: microGosb
redis.uri: redis://192.168.1.72
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

logger:
  levels:
    io.micronaut.context.condition: TRACE
    org.schors: TRACE



