gosb:
  bot:
    new: true
    enabled: true
    # name: "replace_me"
    # token: "replace_me"
    groupId: -1001075972160
  #    groupId: "-417220779"
  data: ms
  #  data: db
  #  data: redis
  battle:
    messages:
      - Битва! Ура, бежим бить!
      - Канальи! Там тысяча чертей!
      - Воруй, полоскай, мафии по жопе дай!
      - А ты! Уже пнул мафию?
      - Мафия сама себя не отпердолит!
      - Очень чешется копыто. А у тебя?
      - Чье кунфу сильнее? Узнай на ТНТ!
      - Лень конечно, но пора на войну!
      - Битва!
      - Соблаговолите пройти в битву!
      - И вновь продолжается бой, и сердцу тревожно в груди...
      - Обед обедом, а война по расписанию!
      - С прискорбием сообщаю что пора в битву
      - Да, это снова я, да - опять пора стрелять!
      - Ля ля ля, жу жу жу, иду бить, не торможу
      - Я из лесу вышел, был сильный понос, и кинул я памперс Грозе прямо в нос!
      - Сижу на берегу реки, смотрю на трупы врагов
    ends:
      - Сливаем допы!
  birthdays:
    - name: "Афина"
      date: "12/12/1980"
    - name: "Фурия"
      date: "19/08/1980"

microstream:
  rest:
    enabled: true
    path: ms
  storage:
    event:
      root-class: 'org.schors.gos.micro.model.Data'
      storage-directory: build/microstream$gosb
      channel-count: 4
      channel-directory-prefix: 'channel_'
      data-file-prefix: 'channel_'
      data-file-suffix: 'dat'

micronaut:
  server:
    port: 9090
  http:
    services:
      telegram:
        urls:
          - https://api.telegram.org/bot${gosb.bot.token}/
        read-timeout: 75s
        connect-timeout: 75s
        logger-name: telegram
  router:
    static-resources:
      assets:
        enabled: true
        mapping: /**
        paths: classpath:battle
  application:
    name: microGosb

logger:
  levels:
    io.micronaut: INFO
    io.micronaut.context: INFO
    org.schors: TRACE
    org.telegram: INFO

endpoints:
  info:
    enabled: true
    sensitive: false

kubernetes:
  client:
    config-maps:
      paths:
        - /etc/configuration

