---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: dd4336db84a17e0db6d5652ff891e13de7386b2e
    app.quarkus.io/build-timestamp: 2022-11-01 - 15:28:23 +0000
  labels:
    app.kubernetes.io/name: gosb
    app.kubernetes.io/version: "0.1"
  name: gosb
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: gosb
    app.kubernetes.io/version: "0.1"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: dd4336db84a17e0db6d5652ff891e13de7386b2e
    app.quarkus.io/build-timestamp: 2022-11-01 - 15:28:23 +0000
  labels:
    app.kubernetes.io/name: gosb
    app.kubernetes.io/version: "0.1"
  name: gosb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gosb
      app.kubernetes.io/version: "0.1"
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: dd4336db84a17e0db6d5652ff891e13de7386b2e
        app.quarkus.io/build-timestamp: 2022-11-01 - 15:28:23 +0000
      labels:
        app.kubernetes.io/name: gosb
        app.kubernetes.io/version: "0.1"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: flicus/gosb:0.1
          imagePullPolicy: Never
          name: gosb
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
